---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.24
  labels:
    derrick.service: rtcUploadMonitor
  name: rtcUploadMonitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    derrick.service: rtcUploadMonitor
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.24
  labels:
    derrick.service: rtcUploadMonitor
  name: rtcUploadMonitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: rtcUploadMonitor
    spec:
      containers:
      - image: monitor-log-upload:1.0
        name: web
        ports:
        - containerPort: 8080